### ISSUE TITLE
Password set to Cryptopus login password after editing

### ISSUE THREAD

**Issue by kallies** [puzzle/cryptopus#54]
After editing a (private) entry (.../de/teams/x/groups/y/accounts/z/edit), editing the description (account[description]) and saving the entry the password changes from the one before to the Cryptopus login password (account[cleartext_password]).

When I remove the the entry in the password input it doesn't override the password (as expected).

**Comment by janissbinder** [comment]
I tried to reproduce your case without success. If you're using a password manager, It could be, that the manager fills the password field with your LDAP password, because he saved it for the website. Could you please try to turn off the password manger if you're using one and try it again?

On Account editing, the password field should not be filled out by default. It wouldn't make sense at all to fill it out, cause you couldn't read it.

**Comment by kallies** [comment]
Wasn't able to reproduce it in private browsing sessions. As mentioned, it could be a password manager issue.

Thanks @janissbinder
